export const mockListDocuments = [
    {
      id: 1,
      typeDeFichier: "pdf",
      nomDocument: "Rapport Annuel 2025",
      equipe: "Finance",
      nomCreateur: "Alice Dupont",
      tailleFichier: "2.3 MB",
      dateDeCreation: "2025-11-01",
    },
    {
      id: 2,
      typeDeFichier: "word",
      nomDocument: "Plan Marketing Q4",
      equipe: "Marketing",
      nomCreateur: "Bob Martin",
      tailleFichier: "1.8 MB",
      dateDeCreation: "2025-10-28",
    },
    {
      id: 3,
      typeDeFichier: "excel",
      nomDocument: "Budget Prévisionnel",
      equipe: "Finance",
      nomCreateur: "Clara Dubois",
      tailleFichier: "3.2 MB",
      dateDeCreation: "2025-09-15",
    },
    {
      id: 4,
      typeDeFichier: "powerpoint",
      nomDocument: "Présentation Produit",
      equipe: "Ventes",
      nomCreateur: "David Leroy",
      tailleFichier: "4.1 MB",
      dateDeCreation: "2025-08-22",
    },
    {
      id: 5,
      typeDeFichier: "texte",
      nomDocument: "Procès-Verbal Réunion",
      equipe: "RH",
      nomCreateur: "Eva Moreau",
      tailleFichier: "0.9 MB",
      dateDeCreation: "2025-07-30",
    },
    {
      id: 6,
      typeDeFichier: "Image",
      nomDocument: "Procès-Verbal Réunion",
      equipe: "RH",
      nomCreateur: "Eva Moreau",
      tailleFichier: "0.9 MB",
      dateDeCreation: "2025-07-30",
    },
  ];